apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 2.3.0
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    app: node-exporter
  type: ClusterIP
  ports:
  - port: 9100
    name: node-exporter