apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8ssandra-test-triki
  region: ap-south-1
  version: "1.33"

availabilityZones: [ap-south-1a,ap-south-1b,ap-south-1c]

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

managedNodeGroups:
  - name: tb-node
    instanceType: t4g.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    labels: { tb-node: allowed }
    availabilityZones: ["ap-south-1a"]
    privateNetworking: true
    volumeType: gp3
    volumeSize: 30

  - name: k8ssandra-r1a
    instanceType: t4g.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    labels: { cassandra: allowed }
    availabilityZones: ["ap-south-1a"]
    privateNetworking: true
    volumeType: gp3
    volumeSize: 30

  - name: k8ssandra-r1b
    instanceType: t4g.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    labels: { cassandra: allowed }
    availabilityZones: ["ap-south-1b"]
    privateNetworking: true
    volumeType: gp3
    volumeSize: 30

  - name: k8ssandra-r1c
    instanceType: t4g.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    labels: { cassandra: allowed }
    availabilityZones: ["ap-south-1c"]
    privateNetworking: true
    volumeType: gp3
    volumeSize: 30

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:      # add IAM and service account
      ebsCSIController: true