apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupSchedule
metadata:
  name: tenday-full-backup
  namespace: thingsboard
spec:
  backupSpec:
    cassandraDatacenter: ap-south-1
    backupType: full
  cronSchedule: "0 2 10,20,30 * *" # ““At 02:00 on day-of-month 10, 20, and 30.”
  disabled: false
---
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupSchedule
metadata:
  name: tenday-28feb-full-backup
  namespace: thingsboard
spec:
  backupSpec:
    cassandraDatacenter: ap-south-1
    backupType: full
  cronSchedule: "0 2 28 2 *" # “At 02:00 on day-of-month 28 in February.”
  disabled: false