apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupSchedule
metadata:
  name: daily-diff-backup
  namespace: thingsboard
spec:
  backupSpec:
    cassandraDatacenter: ap-south-1
    backupType: differential
  cronSchedule: "0 2 1-9,11-19,21-31 * *" # “At 02:00 on every day-of-month from 1 through 9, every day-of-month from 11 through 19, and every day-of-month from 21 through 31.”
  disabled: false