# TODO - review this, it was barely touched!
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupSchedule
metadata:
  name: daily-diff-backup
  namespace: thingsboard
spec:
  backupSpec:
    cassandraDatacenter: ap-south-1
    backupType: differential
  cronSchedule: "0 2 * * 0-5" # “At 02:00 on every day-of-week from Sunday through Friday.”
  disabled: false