apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: ClusterIP
  # externalTrafficPolicy: Local
  selector:
    app: prometheus-server
  ports:
  - port: 9090
    targetPort: 9090
    name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  labels:
    app: prometheus-server
  name: prometheus-pvc
spec:
  storageClassName: gp3
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
