# TODO - review this, it was barely touched!
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupSchedule
metadata:
  name: monthly-full-backup
  namespace: thingsboard
spec:
  backupSpec:
    cassandraDatacenter: ap-south-1
    backupType: full
  cronSchedule: "0 2 7 * *" # “At 02:00 on day-of-month 7.”
  disabled: false