apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cassandra-cluster
  namespace: thingsboard
spec:

  cassandra:
    serverVersion: "5.0.4"
    clusterName: "cassandra"
    datacenters:
      - metadata:
          name: ap-south-1
        size: 3
        racks:
          - name: r1a
            nodeAffinityLabels:
              cassandra: allowed
              "topology.kubernetes.io/zone": "ap-south-1a"
          - name: r1b
            nodeAffinityLabels:
              cassandra: allowed
              "topology.kubernetes.io/zone": "ap-south-1b"
          - name: r1c
            nodeAffinityLabels:
              cassandra: allowed
              "topology.kubernetes.io/zone": "ap-south-1c"
    resources:
      requests:
        cpu: 1000m
        memory: 6Gi
      limits:
        cpu: 2000m
        memory: 6Gi
    config:
      jvmOptions:
        heap_initial_size: 4G # same as "-Xmx"
        heap_max_size: 4G # same as "-Xms" or "MAX_HEAP_SIZE"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp3-retainable
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
    # telemetry:
    #   prometheus:
    #     enabled: true

  medusa:
    containerResources: # TODO - tune this
      requests:         #   I have
        cpu: 10m        #       no
        memory: 100Mi   #         idea
      limits:           #           what
        cpu: 1000m      #             should be
        memory: 750Mi   #               here
    initContainerResources:
      requests:         #   here
        cpu: 10m        #       as
        memory: 10Mi    #         well
      limits:           #
        cpu: 100m       #           (those should be tiny I think)
        memory: 50Mi    #
    storageProperties:
      storageProvider: s3
      region: ap-south-1
      storageSecretRef:
        name: medusa-s3-secret
      bucketName: k8ssandra-test-triki-backups
    purgeBackups: false # configure lifecycle on S3 bucket instead

  reaper:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: cassandra-reaper
                operator: In
                values:
                  - allowed
    deploymentMode: SINGLE
    autoScheduling:
      # see https://cassandra-reaper.io/docs/configuration/reaper_specific/#autoscheduling
      enabled: true
      initialDelayPeriod: PT10M # 10 minutes, default is 15 seconds
      periodBetweenPolls: PT10M
      timeBeforeFirstSchedule: PT5M
      scheduleSpreadPeriod: PT6H
      repairType: INCREMENTAL
      percentUnrepairedThreshold: 10
    resources:          # TODO - tune this
      requests:         #   I have
        cpu: 200m       #       no
        memory: 1Gi     #         idea
      limits:           #           what
        cpu: 2000m      #             should be
        memory: 3Gi     #               here
    heapSize: 2Gi # default
    # telemetry:
    #   prometheus:
    #     enabled: true