apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cassandra-cluster
  namespace: thingsboard
spec:

  cassandra:
    serverVersion: "5.0.4"
    clusterName: "cassandra"
    datacenters:
      - metadata:
          name: ap-south-1
        size: 3
        racks:
          - name: r1a
            nodeAffinityLabels:
              cassandra: allowed
              "topology.kubernetes.io/zone": "ap-south-1a"
          - name: r1b
            nodeAffinityLabels:
              cassandra: allowed
              "topology.kubernetes.io/zone": "ap-south-1b"
          - name: r1c
            nodeAffinityLabels:
              cassandra: allowed
              "topology.kubernetes.io/zone": "ap-south-1c"
    resources:
      requests:
        cpu: 1000m
        memory: 6Gi
      limits:
        cpu: 2000m
        memory: 6Gi
    config:
      jvmOptions:
        heap_initial_size: 4G # same as "-Xmx"
        heap_max_size: 4G # same as "-Xms" or "MAX_HEAP_SIZE"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp3-retainable
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 90Gi # 40gb estimate, leave +- 50% per compaction best practice
    # telemetry:
    #   prometheus:
    #     enabled: true

  medusa:
    containerImage:
      name: medusa
      repository: k8ssandra
      tag: "0.24.1"
    containerResources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 750Mi
    initContainerResources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        cpu: 100m
        memory: 50Mi
    storageProperties:
      storageProvider: s3
      region: ap-south-1
      storageSecretRef:
        name: medusa-s3-secret
      bucketName: k8ssandra-test-triki-backups
    purgeBackups: false # configure lifecycle on S3 bucket instead

  reaper:
    containerImage:
      name: cassandra-reaper
      repository: thelastpickle
      tag: "4.0.0-beta4"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: cassandra-reaper
                operator: In
                values:
                  - allowed
    deploymentMode: SINGLE
    autoScheduling:
      # see https://cassandra-reaper.io/docs/configuration/reaper_specific/#autoscheduling
      enabled: true
      initialDelayPeriod: PT10M # 10 minutes, default is 15 seconds
      periodBetweenPolls: PT10M
      timeBeforeFirstSchedule: PT5M
      scheduleSpreadPeriod: PT6H
      repairType: INCREMENTAL
      percentUnrepairedThreshold: 10
    resources:
      requests:
        cpu: 50m
        memory: 2Gi
      limits:
        cpu: 100m
        memory: 2Gi
    heapSize: 2Gi # default
    # telemetry:
    #   prometheus:
    #     enabled: true